apiVersion: v1
kind: Service
metadata:
  name: untitledproject-service
spec:
  selector:
    app: untitledproject
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: untitledproject
spec:
  selector:
    matchLabels:
      app: untitledproject
  replicas: 4
  template:
    metadata:
      labels:
        app: untitledproject
    spec:
      containers:
      - name: untitledproject
        image: untitledproject:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000